[database]
server = "15.204.52.56,1435"
database = "suprasac"
username = "ops"
password = "Suporte2022=Mais"


[email]
senha = "Benicio@2024"

[telegram]
token = "8922477706:AAFpgSxQyz8YR_S3ZAaX0_tMlrebq9SWspk"